new run4

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -30,6 +30,12 @@ jobs:
 
       - name: Ejecutar pruebas con Maven
         run: mvn clean verify
+      - name: Mostrar errores del failsafe
+        if: failure()
+        run: |
+          echo "==== Failsafe Error Logs ===="
+          ls -la target/failsafe-reports || echo "No se encontró la carpeta failsafe-reports"
+          cat target/failsafe-reports/*.txt || echo "No se encontró archivo de error detallado"
 
       - name: Subir reporte Serenity
         if: always()
